name: bpay
description: BPay - Crypto to Cash Trading Platform
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  web_socket_channel: ^2.4.0
  shared_preferences: ^2.2.2
  image_picker: ^1.0.7
  provider: ^6.1.1
  intl: ^0.19.0
  cached_network_image: ^3.3.1
  local_auth: ^2.3.0
  flutter_secure_storage: ^9.2.2
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
