plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "c:\\Users\\USER\\bpay_app\\flutter_app\\build\\web"
publishOrigin = "config"
base = "c:\\Users\\USER\\bpay_app\\flutter_app"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]